field.widget.settings.better_links_field_widget:
  type: mapping
  label: 'Better Link settings'
  mapping:
    placeholder_url:
      type: string
      label: 'Placeholder for URL'
    placeholder_title:
      type: label
      label: 'Placeholder for link text'
    better_links_class_mode:
      type: string
      label: 'Method for adding class'
    better_links_class_force:
      type: string
      label: 'Classes in force method'
    better_links_class_select:
      type: string
      label: 'Classes in select method'
    better_links_target_mode:
      type: string
      label: 'Method for adding target'
    better_links_target_force:
      type: string
      label: 'Targets in force method'
